### PR TITLE
Create PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by hpeninah**

### CODE REVIEW

**Comment by hpeninah** [comment]
Just needed to pull the pull request template for github pulls

**Review by YTyler — COMMENTED** [review]
should this be a pull request to a dev branch?

**Comment by YTyler** [comment]
I see now that the issue template commit defaults to main

**Comment by hpeninah** [comment]
Yeah, templates for issues and pull requests automatically go to the default branch which is main

**Review by j-m-smith426 — APPROVED** [review]
looks good

**Pull request merged**
