### PR TITLE
Integrate Batches screens to dev-branch.

### PR DESCRIPTION
**Pull request by redoral**
## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] I have read the **CONTRIBUTING** document.
-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
-   [x] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by hpeninah — APPROVED** [review]
Looks good!

**Review by YTyler — COMMENTED** [review]
- Its my understanding that coverage should be ignored
- If you want to ignore package-lock.json, you'd have to remove the cached versions from git. Otherwise it will continue to track the file.
- Looks good, looking forward to seeing the front end and back ends together

**Comment by Kaichloe** [comment]
LGTM

**Review by j-m-smith426 — APPROVED** [review]
Looks good App will need changed eventually

**Pull request merged**
